#!/bin/bash

dateThen=$(date +%s)


sendMail(){
    if [[ dateNow-dateThen -gt 300 ]] # for five minutes don't mail
    then
           dateThen=$(date +%s)
           subjectDate=$(date +%d-%b-%y)
           /home/parapsychic/.bin/mailer "febinkdominic.fkd@gmail.com" "Wonderland Machine: BATTERY LOW $subjectDate" "Battery at $BATCHARGE"
           notify-send -u critical "MAIL SENT" "Battery mail sent to email"

           echo $dateThen
    fi

}

while true
do
    BATCHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
    BATSTAT=$(cat /sys/class/power_supply/BAT0/status)

    if [ "$BATSTAT" = 'Discharging' ]
    then
        #if under 6%, just shutdown
        if [ $BATCHARGE -lt 6 ]
        then
            # not the cleanest way to poweroff, but this works ig
            poweroff
        fi
        
        #show notifications
        if [ $BATCHARGE -lt 10 ]
        then
            dateNow=$(date +%s)
            dateThen=$(sendMail)
            notify-send -u critical "BATTERY TOO LOW!" "Battery below $BATCHARGE%"

        elif [ $BATCHARGE -lt 20 ]
        then
            dateNow=$(date +%s)
            dateThen=$(sendMail)
            notify-send -u critical "BATTERY LOW!" "Battery below $BATCHARGE%$status"

        elif [ $BATCHARGE -lt 30 ]
        then
            dateNow=$(date +%s)
            dateThen=$(sendMail)
            notify-send -u normal "Below $BATCHARGE%" "This might be a very good time to start charging"

        elif [ $BATCHARGE -lt 50 ]
        then
            notify-send -u low "$BATCHARGE% alert" "Battery at $BATCHARGE%"

        fi
    fi
    sleep 60
done

